apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "postgresql.example.com/v1alpha1",
          "kind": "Postgresql",
          "metadata": {
            "name": "example-postgresql"
          },
          "spec": {
            "image": "postgres:10.4",
            "pvc": "postgres-pvc-1",
            "size": 1
          }
        },
        {
          "apiVersion": "postgresql.example.com/v1alpha1",
          "kind": "PgBackup",
          "metadata": {
            "name": "example-pgbackup"
          },
          "spec": {
            "backupFile": "data.sql",
            "dbName": "supermarket",
            "image": "deekshah86/pgbackuprestore-ibmcloud:1",
            "pgdata": "/var/lib/postgresql/data/pg-backup/",
            "postgresDb": "postgresdb",
            "postgresPassword": "admin123",
            "postgresUser": "postgresadmin",
            "pvc": "postgres-pvc-2",
            "schedule": "*/1 * * * * ",
            "serviceIp": "service.psql.svc.cluster.local"
          }
        },
        {
          "apiVersion": "postgresql.example.com/v1alpha1",
          "kind": "PgRestore",
          "metadata": {
            "name": "example-pgrestore"
          },
          "spec": {
            "backupFile": "data.sql",
            "dbName": "supermarket-03-03-2020.sql;",
            "image": "deekshah86/pgbackuprestore-ibmcloud:1",
            "pgdata": "/var/lib/postgresql/data/pg-restore/",
            "postgresDb": "postgresdb",
            "postgresPassword": "admin123",
            "postgresUser": "postgresadmin",
            "pvc": "postgres-pvc-3",
            "serviceIp": "service.psql.svc.cluster.local"
          }
        }
      ]
    capabilities: Basic Install
  name: postgresql-operator-phases-1-2-3.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: PgBackup
      name: pgbackups.postgresql.example.com
      version: v1alpha1
    - kind: PgRestore
      name: pgrestores.postgresql.example.com
      version: v1alpha1
    - kind: Postgresql
      name: postgresqls.postgresql.example.com
      version: v1alpha1
  description: Placeholder description
  displayName: Postgresql Operator Phases 1 2 3
  install:
    spec:
      deployments:
      - name: postgresql-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: postgresql-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: postgresql-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/deekshah86/postgresql-operator
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: postgresql-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/deekshah86/postgresql-operator
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: postgresql-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - postgresql-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - postgresql.example.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - '*'
        serviceAccountName: postgresql-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - postgres
  - database
  maintainers:
  - email: openlabs@ibm.com
    name: Openlabs
  maturity: alpha
  provider:
    name: Openlabs
  replaces: postgresql-operator-phases-1-2-3.v0.0.0
  version: 0.0.1
