---
- name: start pgbackup cron job
  k8s:
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: '{{ meta.name }}-cronjob-pgbackup'
        namespace: '{{ meta.namespace }}'
      spec:
        replias: 1
        successfulJobsHistoryLimit: 2
        failedJobsHistoryLimit: 1
        schedule: "{{ schedule }}"
        jobTemplate:
          spec:
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: postgres-backup
                    image: "{{ image }}"
                    ports:
                      - containerPort: 5432
                    env:
                      - name: SERVICE_IP
                        value: "{{ service_ip }}"
                      - name: DB_NAMES
                        value: "{{ db_name }}"
                      - name: POSTGRES_DB
                        value: "{{ postgres_db }}"
                      - name: POSTGRES_USER
                        value: "{{ postgres_user }}"
                      - name: POSTGRES_PASSWORD
                        value: "{{ postgres_password }}"
                      - name: PGDATA
                        value: "{{ pgdata }}"
                    envFrom:
                      - configMapRef:
                          name: pgbackup-cm
                    volumeMounts:
                    - name: postgresql-data
                      mountPath: "/var/lib/postgresql/data"
                    command: ["/bin/sh","-c"]
                    args: ["bash backup-db.sh "]
                volumes:
                - name: postgresql-data
                  persistentVolumeClaim:
                    claimName: "{{ pvc }}"
