---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgbackup
  namespace: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: deekshah86/pgbackuprestore-ibmcloud:1 
          ports:
            - containerPort: 5432
          env:
            - name: SERVICE_IP
              value: postgres-1-service.pgdb.svc.cluster.local
            - name: DB_NAMES
              value: supermarket
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: postgresadmin
            - name: POSTGRES_PASSWORD
              value: admin123
            - name: PGDATA
              value: /var/lib/postgresql/data/pg-backup/
          envFrom:
            - configMapRef:
                name: pgbackup-cm
          volumeMounts:
            - name: postgresql-data
              mountPath: "/var/lib/postgresql/data"
          command: ["/bin/sh","-c"]
          args: ["bash backup-db.sh "]
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgres-pvc-11
---
apiVersion: v1
kind: Service
metadata:
  name: pgbackup
  namespace: pgdb
labels:
  app: postgres
spec:
  ports:
  - name: database
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
