apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-cm
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data/db-files/
